### PR TITLE
Add Scala 2.13 build

### PR DESCRIPTION
**Pull request by markus1189**
Build also for Scala 2.13

### CODE REVIEW

**Comment by markus1189** [comment]
Under 2.13 we have some deprecation warnings about `.right.value` because `.right` is deprecated (again?!)  I'm not sure whether we want to fix this right now by e.g. using `.toOption.value` because of https://github.com/scalatest/scalatest/pull/975

**Comment by markus1189** [comment]
Should be merged *after* #38

**Comment by froth** [comment]
Nice! Do you think we can benefit from https://docs.scala-lang.org/sips/byname-implicits.html in 2.13 without writing two different versions of the shapeless codecs?

**Comment by froth** [comment]
> Under 2.13 we have some deprecation warnings about `.right.value` because `.right` is deprecated (again?!) I'm not sure whether we want to fix this right now by e.g. using `.toOption.value` because of [scalatest/scalatest#975](https://github.com/scalatest/scalatest/pull/975)

We should provide negative community feedback to dedeprecate it (again!)
Seriously not sure. Why does scalatest not provide a new rightvalue? I am unsure whether is misslike .toOption.value or the deprecation warnings more.

**Pull request merged**
