### PR TITLE
Wart remover

### LINKED ISSUE #141: linting

### PR DESCRIPTION
**Pull request by froth**
fixes #141

### CODE REVIEW

**Comment by froth** [comment]
@markus1189 the Any and Nothing warnings seem like false positives, right? (have not looked at the wart remover outputs for the tests, so please ignore at you discretion)

**Comment by markus1189** [comment]
I'll have a look tomorrow 😉

**Comment by markus1189** [comment]
Yeah well...

It's not a false positive, the inferred type does sometimes contain `Any` and `Nothing`, e.g.:

```scala
PartialFunction.empty // has type: PartifalFunction[Any, Nothing]
```

unless you explicitly give the type params to `empty`.  It works out in the end due to co/contra-variance though.

Is it a severe problem? No.  Could it in some special cases lead to weird errors? Yes, for example if the typeclass is not co/contra-variant, it will fail to find the instance without helping the compiler by giving types.

I think at the end it's a bit of a matter of strictness, whether one wants to enforce this everywhere or not.  It's a tradeoff between having to state types in more places vs. protection from weird inference issues. :shrug:

**Comment by froth** [comment]
Hmmm, yeah the PartialFunction think would be an easy enough fix but the 
`implicit def vectorDecoder[A: BsonDecoder]: BsonDecoder[Vector[A]] = iterableDecoder` lines are a little more involved I fear.

**Comment by markus1189** [comment]
The vectorDecoder is actually an issue with our iterableDecoder...  I fixed some more issues in: 3ea2a6342b00b24015b531171664511c67a8613e

**Comment by froth** [comment]
Ah, nice. I always had "really understanding that thing" on my todo list :)

**Comment by froth** [comment]
I am not sure of whether I like the trade of, but I will put in the effort to make wartremover happy and then see how I like the result.

**Comment by froth** [comment]
@markus1189 In opted for not wanting the Any and Nothing Warts... Wanna have another look?

**Review by markus1189 — APPROVED** [review]
LGTM, in theory we would not need the `Either.rightNec` instead of `Right`, but does not hurt either I guess :shrug:

**Pull request merged**
